"""Imagery ORM models. Catalog rows in `public`; subscriptions and ingestion
jobs in the per-tenant schema (no `__table_args__["schema"]` — search_path
resolves). data_model § 6.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from sqlalchemy import (
    ARRAY,
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.shared.db.base import UUID_V7_DEFAULT, Base, TimestampedMixin


class ImageryProvider(Base, TimestampedMixin):
    """`public.imagery_providers` — curated provider catalog."""

    __tablename__ = "imagery_providers"
    __table_args__ = {"schema": "public"}

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=UUID_V7_DEFAULT
    )
    code: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("TRUE"))
    config_schema: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )


class ImageryProduct(Base, TimestampedMixin):
    """`public.imagery_products` — products offered by each provider."""

    __tablename__ = "imagery_products"
    __table_args__ = {"schema": "public"}

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=UUID_V7_DEFAULT
    )
    provider_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("public.imagery_providers.id", ondelete="RESTRICT"),
        nullable=False,
    )
    code: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    resolution_m: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False)
    revisit_days_avg: Mapped[Decimal] = mapped_column(Numeric(4, 2), nullable=False)
    bands: Mapped[list[str]] = mapped_column(ARRAY(Text), nullable=False)
    supported_indices: Mapped[list[str]] = mapped_column(ARRAY(Text), nullable=False)
    cost_tier: Mapped[str] = mapped_column(Text, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("TRUE"))


class ImageryAoiSubscription(Base, TimestampedMixin):
    """`tenant_<id>.imagery_aoi_subscriptions` — what to fetch for which block."""

    __tablename__ = "imagery_aoi_subscriptions"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=UUID_V7_DEFAULT
    )
    block_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("blocks.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Cross-schema FK (logical) to public.imagery_products.id.
    product_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    # NULL = use tenant default (per data_model § 6.4 + Q3 in the PR-A plan).
    cadence_hours: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cloud_cover_max_pct: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("TRUE"))
    last_successful_ingest_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_attempted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class ImageryIngestionJob(Base):
    """`tenant_<id>.imagery_ingestion_jobs` — one row per pipeline run.

    Not a TimestampedMixin: the spec only stores `requested_at` /
    `started_at` / `completed_at`, not the soft-delete + updated_at
    pair. Status mutates throughout the pipeline.
    """

    __tablename__ = "imagery_ingestion_jobs"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=UUID_V7_DEFAULT
    )
    subscription_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey(
            "imagery_aoi_subscriptions.id",
            # Auto-generated by naming_convention exceeds Postgres' 63-char
            # identifier limit; pin the short form to match migration 0003.
            name="fk_imagery_ingestion_jobs_subscription_id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )
    block_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    product_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    scene_id: Mapped[str] = mapped_column(Text, nullable=False)
    scene_datetime: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    cloud_cover_pct: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)
    valid_pixel_pct: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    stac_item_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    assets_written: Mapped[dict[str, Any] | list[Any] | None] = mapped_column(JSONB, nullable=True)
