tempo:
  retention: 168h          # 7 days hot
  storage:
    trace:
      backend: s3
      s3:
        bucket: missionagre-tempo-traces
        endpoint: s3.me-south-1.amazonaws.com
        region: me-south-1
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write

serviceMonitor:
  enabled: true
