apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agripulse-workers.fullname" . }}
  labels:
    {{- include "agripulse-workers.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ tpl ($v | toString) $ | quote }}
  {{- end }}
