{{- range $name, $workload := .Values.workloads -}}
{{- if and $workload.enabled $workload.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-%s" (include "missionagre-workers.fullname" $) $name }}
  labels:
    {{- include "missionagre-workers.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $workload.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "missionagre-workers.selectorLabels" (dict "root" $ "name" $name) | nindent 6 }}
{{- end }}
{{- end }}
