{{- define "agripulse-tile-server.fullname" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "agripulse-tile-server.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (printf "%s-tile-server" .Release.Name) .Values.serviceAccount.name -}}
{{- else -}}
{{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end -}}

{{- define "agripulse-tile-server.imageRef" -}}
{{- /* Overlay key is `tileServer` (camelCase) â€” the chart name has a
       hyphen but YAML keys generated by the yq bump loop don't. */ -}}
{{- $tag := default .Chart.AppVersion (default .Values.image.tag .Values.global.images.tileServer.tag) -}}
{{- printf "%s:%s" .Values.image.repository $tag -}}
{{- end -}}

{{- define "agripulse-tile-server.labels" -}}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: agripulse
app.kubernetes.io/component: tile-server
{{- end -}}

{{- define "agripulse-tile-server.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: tile-server
{{- end -}}
