{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore.name }}
  labels:
    {{- include "missionagre.shared.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.clusterSecretStore.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.clusterSecretStore.serviceAccount.name }}
            namespace: {{ .Values.externalSecrets.clusterSecretStore.serviceAccount.namespace }}
{{- end }}
