apiVersion: v1
kind: ConfigMap
metadata:
  name: agripulse-app-config
  labels:
    {{- include "agripulse.shared.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.appConfig.serviceName | quote }}
  AWS_DEFAULT_REGION: {{ .Values.appConfig.region | quote }}
  APP_LOG_LEVEL: {{ .Values.appConfig.log.level | quote }}
  APP_LOG_FORMAT: {{ .Values.appConfig.log.format | quote }}
