{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agripulse-frontend.fullname" . }}
  labels:
    {{- include "agripulse-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ printf "%s.%s" .Values.ingress.hostPrefix .Values.global.envHost }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ printf "%s.%s" .Values.ingress.hostPrefix .Values.global.envHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "agripulse-frontend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
