"""Signals ORM models. All three tables live in the per-tenant schema.

`signal_observations` is a TimescaleDB hypertable (no `PRIMARY KEY`
that excludes the time column); we expose `time` + `id` as the replay
unique key. Application-level UUID v7 keeps inserts ordered.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Numeric,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.shared.db.base import UUID_V7_DEFAULT, Base, TimestampedMixin


class SignalDefinition(Base, TimestampedMixin):
    """`tenant_<id>.signal_definitions` — what kinds of signals exist."""

    __tablename__ = "signal_definitions"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=UUID_V7_DEFAULT
    )
    code: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    value_kind: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    categorical_values: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    value_min: Mapped[Decimal | None] = mapped_column(Numeric(12, 4), nullable=True)
    value_max: Mapped[Decimal | None] = mapped_column(Numeric(12, 4), nullable=True)
    attachment_allowed: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("FALSE")
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("TRUE")
    )


class SignalAssignment(Base, TimestampedMixin):
    """`tenant_<id>.signal_assignments` — which farms/blocks a definition applies to.

    A row with both `farm_id` and `block_id` NULL means tenant-wide.
    """

    __tablename__ = "signal_assignments"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=UUID_V7_DEFAULT
    )
    signal_definition_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("signal_definitions.id", ondelete="CASCADE"),
        nullable=False,
    )
    farm_id: Mapped[UUID | None] = mapped_column(PG_UUID(as_uuid=True), nullable=True)
    block_id: Mapped[UUID | None] = mapped_column(PG_UUID(as_uuid=True), nullable=True)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("TRUE")
    )


class SignalObservation(Base):
    """`tenant_<id>.signal_observations` — TimescaleDB hypertable.

    No PK on a single column: TimescaleDB requires the partition column
    in any unique constraint. We declare `(time, id)` as the replay
    UNIQUE; UUID v7 ids generated by the service layer keep inserts
    monotonic for the time-id pair.
    """

    __tablename__ = "signal_observations"
    __table_args__: tuple[UniqueConstraint | dict[str, object], ...] = (
        UniqueConstraint("time", "id", name="uq_signal_observations_time_id"),
        {},
    )

    time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, primary_key=True
    )
    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), nullable=False, server_default=UUID_V7_DEFAULT, primary_key=True
    )
    signal_definition_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    block_id: Mapped[UUID | None] = mapped_column(PG_UUID(as_uuid=True), nullable=True)
    farm_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    value_numeric: Mapped[Decimal | None] = mapped_column(Numeric(14, 4), nullable=True)
    value_categorical: Mapped[str | None] = mapped_column(Text, nullable=True)
    value_event: Mapped[str | None] = mapped_column(Text, nullable=True)
    value_boolean: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    # value_geopoint stored as PostGIS geometry(Point,4326); not exposed via ORM
    # (consumers go through the repository which renders GeoJSON).
    attachment_s3_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    recorded_by: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False)
    inserted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
